version: '1'

services:
  client:
    container_name: client
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - "4000:4000"
    